# Generated by Django 6.0.3 on 2026-09-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_timestamps_platformcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['full_name']},
        ),
    ]
