# Generated by Django 6.1.1 on 2026-09-07 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=150)),
                ('difficulty_level', models.CharField(default='Beginner', max_length=50)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='trainers.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('repetitions', models.PositiveIntegerField(default=10)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('rest_time', models.CharField(blank=True, max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='fitness.workoutplan')),
            ],
            options={
                'unique_together': {('workout_plan', 'user')},
            },
        ),
    ]
